In [2]:
import os
import pandas as pd
import matplotlib.pyplot as plt
from functions import functions

In [20]:
#data1 = pd.read_csv("/lirneasia/data/lacuna/raw/Leco_data/First 500/1/LOAD_PROFILE_HISTORICAL_READINGS_INVENTORY_17_04_2024.csv")
#data2 = pd.read_csv("/lirneasia/data/lacuna/processed/sm_april_2024_dump/3LOAD_PROFILE_HISTORICAL_READINGS_INVENTORY_17_04_2024.csv", low_memory=False)

survey_pool = pd.read_csv('/lirneasia/data/lacuna/raw/z_other/LA_lacuna_sample.csv')
survey_data = pd.read_csv('/lirneasia/data/lacuna/raw/Survey_data/Survey_wave_1_may_29.csv', low_memory=False)

## Getting consumption data into a consistant format

In [2]:
data1.columns

Index(['SERIAL', 'CUSTOMER_REF', 'TIMESTAMP', 'OBIS', 'DATE', 'TIME',
       'IMPORT_KWH (kWh)', 'EXPORT_KWH (kWh)', 'IMPORT_KVARH (kvarh)',
       'EXPORT_KVARH (kvarh)', 'PHASE_A_INST._CURRENT (A)',
       'PHASE_B_INST._CURRENT (A)', 'PHASE_C_INST._CURRENT (A)',
       'PHASE_A_INST._VOLTAGE (V)', 'PHASE_B_INST._VOLTAGE (V)',
       'PHASE_C_INST._VOLTAGE (V)', 'POWER_FACTOR', 'AVG._IMPORT_KW (kW)',
       'AVG._EXPORT_KW (kW)', 'AVG._IMPORT_KVA (kVA)', 'AVG._EXPORT_KVA (kVA)',
       'AVG._CURRENT (V)', 'AVG._VOLTAGE (V)'],
      dtype='object')

In [3]:
data2.columns

Index(['serial', 'customerref', 'timestamp', 'obis', 'date', 'time',
       'importkwh(kwh)', 'exportkwh(kwh)', 'importkvarh(kvarh)',
       'exportkvarh(kvarh)', 'phaseainstcurrent(a)', 'phasebinstcurrent(a)',
       'phasecinstcurrent(a)', 'phaseainstvoltage(v)', 'phasebinstvoltage(v)',
       'phasecinstvoltage(v)', 'powerfactor', 'avgimportkw(kw)',
       'avgexportkw(kw)', 'avgimportkva(kva)', 'avgexportkva(kva)',
       'avgcurrent(v)', 'avgvoltage(v)'],
      dtype='object')

In [21]:
def clean_column_names(col):
    original_col = col
    col = col.lower()
    
    col = col.replace(' ', '')
    col = col.replace('.', '')
    col = col.replace('_', '')
    
    if col == 'instpowerfactor':
        col = 'powerfactor'
    elif col == 'powerfactor1':
        col = 'powerfactor'
    
    return col

In [41]:
data = data1

data.columns = [clean_column_names(col) for col in data.columns]

columns = data.columns

columns

Index(['serial', 'customerref', 'timestamp', 'obis', 'date', 'time',
       'importkwh(kwh)', 'exportkwh(kwh)', 'importkvarh(kvarh)',
       'exportkvarh(kvarh)', 'phaseainstcurrent(a)', 'phasebinstcurrent(a)',
       'phasecinstcurrent(a)', 'phaseainstvoltage(v)', 'phasebinstvoltage(v)',
       'phasecinstvoltage(v)', 'powerfactor', 'avgimportkw(kw)',
       'avgexportkw(kw)', 'avgimportkva(kva)', 'avgexportkva(kva)',
       'avgcurrent(v)', 'avgvoltage(v)'],
      dtype='object')

In [48]:
root_folder = '/lirneasia/data/lacuna/raw/Leco_data/Second 500'

for folder_name in range(1, 11):
    folder_path = os.path.join(root_folder, str(folder_name))
    
    if os.path.exists(folder_path):
        files = os.listdir(folder_path)
        
        for file_name in files:
            if file_name.endswith('.csv'):
                file_path = os.path.join(folder_path, file_name)
                
                df = pd.read_csv(file_path, low_memory=False)

                df.columns = [clean_column_names(col) for col in df.columns]

                df = df[columns]
                
                df.to_csv(f'/lirneasia/data/lacuna/processed/sm_april_2024_dump/{folder_name}{file_name}.csv', index=False)
        
    else:
        print('file path doesnt exist')

In [ ]:
#ERROR:  extra data after last expected column
#CONTEXT:  COPY power_consumption_sm, line 2: "22301486,704825209,1696100000000.0,LP,2023-10-01,00:00:00,83.0971,0.0,0.402,9.938,0.0,0.0,0.0,235.0,..."
#COPY 173449

#### For sql Table files

In [8]:
proc = pd.read_csv('/lirneasia/data/lacuna/processed/sm_april_2024_dump/1LOAD_PROFILE_HISTORICAL_READINGS_INVENTORY_17_04_2024.csv.csv', low_memory=False)

#with open("wave_1.txt", "w") as file:
for col in proc.columns:
    text = f'"{col}" TEXT,'
    print(text)

"serial" TEXT,
"customerref" TEXT,
"timestamp" TEXT,
"obis" TEXT,
"date" TEXT,
"time" TEXT,
"importkwh(kwh)" TEXT,
"exportkwh(kwh)" TEXT,
"importkvarh(kvarh)" TEXT,
"exportkvarh(kvarh)" TEXT,
"phaseainstcurrent(a)" TEXT,
"phasebinstcurrent(a)" TEXT,
"phasecinstcurrent(a)" TEXT,
"phaseainstvoltage(v)" TEXT,
"phasebinstvoltage(v)" TEXT,
"phasecinstvoltage(v)" TEXT,
"powerfactor" TEXT,
"avgimportkw(kw)" TEXT,
"avgexportkw(kw)" TEXT,
"avgimportkva(kva)" TEXT,
"avgexportkva(kva)" TEXT,
"avgcurrent(v)" TEXT,
"avgvoltage(v)" TEXT,

In [10]:
# \"SERIAL\", \"CUSTOMER_REF\",

for col in proc.columns:
    text = f'\\\"{col}\\\",'
    print(text)

\"serial\",
\"customerref\",
\"timestamp\",
\"obis\",
\"date\",
\"time\",
\"importkwh(kwh)\",
\"exportkwh(kwh)\",
\"importkvarh(kvarh)\",
\"exportkvarh(kvarh)\",
\"phaseainstcurrent(a)\",
\"phasebinstcurrent(a)\",
\"phasecinstcurrent(a)\",
\"phaseainstvoltage(v)\",
\"phasebinstvoltage(v)\",
\"phasecinstvoltage(v)\",
\"powerfactor\",
\"avgimportkw(kw)\",
\"avgexportkw(kw)\",
\"avgimportkva(kva)\",
\"avgexportkva(kva)\",
\"avgcurrent(v)\",
\"avgvoltage(v)\",

## Spatial coverage of the recieved data

In [3]:

number1, cusref1 = households_count('/lirneasia/data/lacuna/raw/Leco_data/First 500')
number2, cusref2 = households_count('/lirneasia/data/lacuna/raw/Leco_data/Second 500')

final = number1 + number2

cusref1_unique = set(cusref1)
cusref2_unique = set(cusref2)

combined_unique_cusref = cusref1_unique.union(cusref2_unique)


print(f"Number of households in all the datasets: {final}")

Number of households in all the datasets: 987

#### Checking wheather the households included in the survey pool

In [7]:
account_no_set = set(survey_pool['ACCOUNT_NO'])

all_in_account_no = combined_unique_cusref.issubset(account_no_set)

print(all_in_account_no)

True

#### Number of household data have for the surveyed households

In [9]:
account_no_in_cusref = survey_data['ACCOUNT_NO'].isin(combined_unique_cusref)
count_account_no_in_cusref = account_no_in_cusref.sum()

print(count_account_no_in_cusref)

300

In [20]:
survey_data[survey_data.T_PData_6 == 'non_smart_meter']

,SERIALNO,UniqueID,ACCOUNT_NO,T_PData_1,T_PData_2,T_PData_3,T_PData_4,T_PData_5,T_PData_6,T_PData_7,...,Trimmer_availability,Tile_Cutter_Machine_availability,Sawing_Machine_availability,Wood_Chipping_Machine_availability,Concrete_Mixture_Machine_availability,Hair_Cutting_Machine_availability,Generator_Battery_availability,Bouth_availability,Grill_availability,LA_Unique_ID
0,194742308,GAL005073,403289502,SOMAWANTHA M H T R*,09 MALWATTA TEMPLE RD* DANGEDARA GALLE* GALLE*,,,94718284752,non_smart_meter,GALLE,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10403289502
1,194742589,GAL005050,402747807,NANDASIRI K L*,12 GANGARAMA CROSS RD* MAGALLE GALLE GALLE*,,,94762159101,non_smart_meter,GALLE,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10402747807
3,194743684,BOR007909,708273907,WEERASINGHE H D D G,"54/38, PIRIVENA RD BORALESGAMUWA",112810488,777474762,94777474762,non_smart_meter,NUGEGODA,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10708273907
4,194744078,KOL00924,107193504,S S ATHIKA,1/B/F/10/U/21 LAKSANDA SEVANA SALAMULLA KOLONN...,,,94763088064,non_smart_meter,KOTTE,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10107193504
5,194744079,KOL00916,107144708,K MOORTHY,1/B/F/7/U/29 LAKSANDA SEVANA SALAMULLA KOLONNA...,,,94768525622,non_smart_meter,KOTTE,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10107144708
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2800,197059425,DAL001166,201546004,RANASINGHE K S*,KANDY RD 829/1* THORANA JTN KELANIYA* 0,,,94773243569,non_smart_meter,KELANIYA,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10201546004
2801,197059426,DAL001683,207904004,A S FERNANDO,425/7/1 ROYAL GARDEN-02 WANAWASALA KELANIYA .,,,94773030123,non_smart_meter,KELANIYA,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10207904004
2803,197059428,DAL001963,210911602,L W RUBASINGHE,146/2 NARAMMINIYA RD KELANIYA .,,761485986,94761485986,non_smart_meter,KELANIYA,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10210911602
2804,197059429,DAL001164,201513906,RAMANAYAKE A I K,"236/5, WEDAMULLA MW KELANIYA* 0",112915947,726303344,94765629251,non_smart_meter,KELANIYA,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10201513906
2805,197059430,DAL001112,200840508,UPALI K M*,DEWALA RD 667/17B* PETHIYAGODA KELANIYA* 0,,,94761445825,non_smart_meter,KELANIYA,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10200840508

## Temporal coverage of the recieved data

In [2]:
root_folder = '/lirneasia/data/lacuna/processed/sm_april_2024_dump'

all_summaries = pd.DataFrame()

folder_path = os.path.join(root_folder)
    
if os.path.exists(folder_path):
    files = os.listdir(folder_path)
        
    for file_name in files:
        if file_name.endswith('.csv'):
            file_path = os.path.join(folder_path, file_name)
                
            data = pd.read_csv(file_path, low_memory=False)

            data['date'] = pd.to_datetime(data['date'])
            data['year_month'] = data['date'].dt.to_period('M')

            summary_table = data.groupby(['customerref', 'year_month']).size().reset_index(name='counts')
            summary = summary_table.pivot_table(index='customerref', columns='year_month', values='counts').fillna(0)
            summary = summary.astype(int)

            all_summaries = pd.concat([all_summaries, summary], ignore_index=False)
            #df.to_csv(f'/lirneasia/data/lacuna/processed/sm_april_2024_dump/{folder_name}{file_name}.csv', index=False)
        
else:
    print('file path doesnt exist')

In [3]:
all_summaries = all_summaries.fillna(0).astype(int)

In [4]:
all_summaries.head(50)

year_month   2023-10  2023-11  2023-12  2024-01  2024-03  2024-04  2024-02
customerref
301369805        464        0     1817      192        0        0        0
301461105        280     2300     1200      192        3       12        0
301592302        324     2260      779       96        3       12        0
301610210        294     2278      456       96        4       14        0
301635510        294     2274      480       96        3       12        0
302391804          0        0      442        0        0        0        0
305546505        274     2383     2954      192        3       12        0
305696710        277     2285      480       96        4       14        0
305838104        258     1824     2112      192        3       12        0
305888209        280     2857     1586      192        3       15        0
305930603        274     2287      862      192        3       12        0
305958411        266     2295     1599      192        4       14        0
305961601        266     2871     1570      192        3       12        0
305968806        266     1819     2110      192        3       12        0
306095504        266     1819     1248       96        3       12        0
306096406        266     2871     1186       96        4       14        0
306293911        280     1802      927       96        4       14        0
306415208        282     2759     2095      192        3       12        0
306458603        282     1800     1138      192        3       12        0
306461309        282     2376     1185       96        3       12        0
306554303       2958     2393     2937      191        0        0        0
306574301        281     1915     1982      192        3       15        0
306577205        266     2395     2144       96        3       15        0
306599403        281     2391     1554      192        3       12        0
306626111        282     1914     1170       96        4       14        0
306751401        282     1823     1303      192        3       12        0
306752710        283     1823     1632      192        4       14        0
307559307        280     2761      341       96        4       14        0
307816201        294     1895      724       96        4       14        0
307959608        280     2761        0       96        3       12        0
308117304        283     2398      384       96        3       15        0
308305701        266     2775      802       96        4       14        0
308367510        294     2370     1199       96        4       14        0
308399509        277     2860     2093       96        3       12        0
308603504        266     2871     1664       96        4       14        0
308624404        258     2304      341       96        3       12        0
308985402       2383        0      465        0        0        0        0
309334410        258     2304     1709       96        3       12        0
309391104        280     2281      754       96        3       12        0
309570008        266     2391     1109      192        4       14        0
309570107       2936     2780     1343      192        0        0        0
309846009        258     2879     1185       96        3       12        0
309919511        294     1909     1319       96        4       14        0
310001505        274     2863     2047      192        3       12        0
310218711        192     2852     2940      192        3       12        0
310775707        277     1901     1344       96        3       12        0
310791503        278     1804     2109      192        3       15        0
310807211        229     2856     1229        0        3       15        0
310814504        280     2857     1666       96        3       12        0
310820411        258     2879     2957      192        3       12        0

In [ ]:
all_summaries.to_csv('/lirneasia/data/lacuna/raw/z_other/2024_april_data_dump_datapoints.csv')

In [3]:
april_sum = pd.read_csv('/lirneasia/data/lacuna/raw/z_other/2024_april_data_dump_datapoints.csv', low_memory=False)

In [5]:
april_sum.describe()

,customerref,2023-10,2023-11,2023-12,2024-01,2024-03,2024-04,2024-02
count,9.870000e+02,987.000000,987.000000,987.000000,987.000000,987.000000,987.000000,987.000000
mean,3.212706e+08,506.585613,2119.735562,1373.969605,113.284701,3.496454,8.720365,0.107396
std,1.162405e+08,737.144994,786.012231,773.829230,75.107840,34.617392,20.160784,3.374017
min,1.012617e+08,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.014859e+08,260.000000,1819.000000,843.500000,96.000000,0.000000,0.000000,0.000000
50%,3.058381e+08,271.000000,2286.000000,1190.000000,96.000000,3.000000,12.000000,0.000000
75%,3.089636e+08,283.000000,2855.000000,1819.000000,192.000000,3.000000,14.000000,0.000000
max,7.087936e+08,2976.000000,2880.000000,2961.000000,798.000000,771.000000,433.000000,106.000000

In [3]:
april_sum['2023-10'] = ((april_sum['2023-10'] / 2976)*100).round(2)
april_sum['2023-11'] = ((april_sum['2023-11'] / 2880)*100).round(2)
april_sum['2023-12'] = ((april_sum['2023-12'] / 2976)*100).round(2)
april_sum['2024-01'] = ((april_sum['2024-01'] / 2976)*100).round(2)
april_sum['2024-02'] = ((april_sum['2024-02'] / 2784)*100).round(2)
april_sum['2024-03'] = ((april_sum['2024-03'] / 2976)*100).round(2)
april_sum['2024-04'] = ((april_sum['2024-04'] / 2880)*100).round(2)

In [29]:
oct = (april_sum['2023-10'] > 70).sum()
nov = (april_sum['2023-11'] > 70).sum()
dec = (april_sum['2023-12'] > 70).sum()
jan = (april_sum['2024-01'] > 70).sum()
feb = (april_sum['2024-02'] > 70).sum()
march = (april_sum['2024-03'] > 70).sum()
april = (april_sum['2024-04'] > 70).sum()


print('Number of households out of 1000, that have atleast 70 percent of the data for each month')
print(f'Oct: {oct}, Nov: {nov}, Dec: {dec}, Jan: {jan}, Feb: {feb}, March: {march}, April: {april}')

Number of households out of 1000, that have atleast 70 percent of the data for each month
Oct: 79, Nov: 537, Dec: 196, Jan: 0, Feb: 0, March: 0, April: 0

In [24]:
filtered_indices = april_sum['customerref'].isin(survey_data['ACCOUNT_NO']).values
april_sum_surveyed = april_sum.loc[filtered_indices]

april_sum_surveyed

,customerref,2023-10,2023-11,2023-12,2024-01,2024-03,2024-04,2024-02
0,301369805,15.59,0.00,61.06,6.45,0.00,0.00,0.0
1,301461105,9.41,79.86,40.32,6.45,0.10,0.42,0.0
3,301610210,9.88,79.10,15.32,3.23,0.13,0.49,0.0
4,301635510,9.88,78.96,16.13,3.23,0.10,0.42,0.0
7,305696710,9.31,79.34,16.13,3.23,0.13,0.49,0.0
...,...,...,...,...,...,...,...,...
971,304146711,0.00,0.00,0.00,0.00,0.10,0.42,0.0
979,309013705,8.84,63.19,54.07,6.45,0.10,0.42,0.0
982,309357609,8.77,79.90,15.39,0.00,0.13,0.49,0.0
984,310745710,8.43,63.33,16.13,3.23,0.10,0.42,0.0
985,310754202,8.43,66.67,12.90,3.23,0.10,0.42,0.0

In [26]:
oct = (april_sum_surveyed['2023-10'] < 20).sum()
nov = (april_sum_surveyed['2023-11'] < 20).sum()
dec = (april_sum_surveyed['2023-12'] < 20).sum()
jan = (april_sum_surveyed['2024-01'] > 70).sum()
feb = (april_sum_surveyed['2024-02'] > 70).sum()
march = (april_sum_surveyed['2024-03'] > 70).sum()
april = (april_sum_surveyed['2024-04'] > 70).sum()

print(oct, nov, dec, jan, feb, march, april)

299 25 47 0 0 0 0

In [26]:
cus_list = survey_pool.ACCOUNT_NO

cus_list.to_csv('/lirneasia/data/lacuna/raw/z_other/survey_pool_list.csv', index=False)

In [ ]:
'''Identifying households that doesnt have data rows for all the expected date-time combinations'''


# Creating a DataFrame with all expected date-time combinations

date_range = pd.date_range(start="2023-10-01", end="2023-12-14", freq="15T")

all_combinations = pd.DataFrame([(CUSTOMER_REF, date_time_clean) for CUSTOMER_REF in df['CUSTOMER_REF'].unique()  for date_time_clean in date_range], columns=['CUSTOMER_REF', 'date_time_clean'])

merged_df = pd.merge(all_combinations, df, on=['CUSTOMER_REF', 'date_time_clean'], how='left')

In [ ]:
merged_df = merged_df[['CUSTOMER_REF', 'date_time_clean', 'Import kWh (kWh)', 'Export kWh (kWh)',
       'Import kvarh (kvarh)', 'Export kvarh (kvarh)',
       'Phase A Inst. Current (A)', 'Phase B Inst. Current (A)',
       'Phase C Inst. Current (A)', 'Phase A Inst. Voltage (V)',
       'Phase B Inst. Voltage (V)', 'Phase C Inst. Voltage (V)',
       'Phase ABC Power factor', 'Avg. Import kW (kW)', 'Avg. Export kW (kW)',
       'Avg. Import kVA (kVA)', 'Avg. Export kVA (kVA)', 'Avg. Current (V)',
       'Avg. Voltage (V)', 'Inst. Power factor']].copy

In [10]:
data.isna().sum()

SERIAL                            0
CUSTOMER_REF                      0
TIMESTAMP                         0
OBIS                              0
DATE                              0
TIME                              0
IMPORT_KWH (kWh)                  0
EXPORT_KWH (kWh)                  0
IMPORT_KVARH (kvarh)         111672
EXPORT_KVARH (kvarh)         111672
PHASE_A_INST._CURRENT (A)    106496
PHASE_B_INST._CURRENT (A)    111672
PHASE_C_INST._CURRENT (A)    111672
PHASE_A_INST._VOLTAGE (V)    106496
PHASE_B_INST._VOLTAGE (V)    111672
PHASE_C_INST._VOLTAGE (V)    111672
POWER_FACTOR                      0
AVG._IMPORT_KW (kW)           14494
AVG._EXPORT_KW (kW)           14494
AVG._IMPORT_KVA (kVA)        126166
AVG._EXPORT_KVA (kVA)        126166
AVG._CURRENT (V)             144214
AVG._VOLTAGE (V)             144214
dtype: int64

In [9]:
'''Checking for null values in IMPORT_KWH (kWh) and EXPORT_KWH (kWh) '''

def is_null_in_import(root_folder):

    count = 0

    
    for folder_name in range(1, 11):
        folder_path = os.path.join(root_folder, str(folder_name))
    
        if os.path.exists(folder_path):
            files = os.listdir(folder_path)
        
            for file_name in files:
                if file_name.endswith('.csv'):
                    file_path = os.path.join(folder_path, file_name)
                
                    df = pd.read_csv(file_path, low_memory=False)
                    
                    x = data.isna()['IMPORT_KWH (kWh)'].sum()

                    count += x
                    
        else:
            print(f"Folder '{folder_name}' does not exist.")

    return count

In [10]:
count = is_null_in_import(second)

if count == 0:
    print("No null values for IMPORT KWH (KWH)")

else:
    print("There are null values in IMPORT KWH")

No null values for IMPORT KWH (KWH)

In [ ]:
'''No of households with solar panals or have exported electricity'''


# Group by 'CUSTOMER_REF' and check if at least one non-zero value exists in the 'export' column

non_zero_accounts = data.groupby('CUSTOMER_REF')['EXPORT_KWH (kWh)'].any().reset_index()

non_zero_accounts = non_zero_accounts[non_zero_accounts['EXPORT_KWH (kWh)']]



print("No of household that have exported power: ", len(non_zero_accounts))